"""add warehouse sales tables

Revision ID: 02f85a5748d5
Revises: b0ee18204dd1
Create Date: 2026-07-25 10:35:58.614169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02f85a5748d5'
down_revision: Union[str, Sequence[str], None] = 'b0ee18204dd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_region', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_customers_customer_name'), 'dim_customers', ['customer_name'], unique=True)
    op.create_index(op.f('ix_dim_customers_id'), 'dim_customers', ['id'], unique=False)
    op.create_table('dim_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar_date', sa.Date(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_dates_calendar_date'), 'dim_dates', ['calendar_date'], unique=True)
    op.create_index(op.f('ix_dim_dates_id'), 'dim_dates', ['id'], unique=False)
    op.create_table('dim_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('product_category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_products_id'), 'dim_products', ['id'], unique=False)
    op.create_index(op.f('ix_dim_products_product_name'), 'dim_products', ['product_name'], unique=True)
    op.create_table('fact_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=100), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('date_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['dim_customers.id'], ),
    sa.ForeignKeyConstraint(['date_id'], ['dim_dates.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['dim_products.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_runs.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['ingestion_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'run_id', 'order_id', name='uq_fact_sales_source_run_order')
    )
    op.create_index(op.f('ix_fact_sales_customer_id'), 'fact_sales', ['customer_id'], unique=False)
    op.create_index(op.f('ix_fact_sales_date_id'), 'fact_sales', ['date_id'], unique=False)
    op.create_index(op.f('ix_fact_sales_id'), 'fact_sales', ['id'], unique=False)
    op.create_index(op.f('ix_fact_sales_order_id'), 'fact_sales', ['order_id'], unique=False)
    op.create_index(op.f('ix_fact_sales_product_id'), 'fact_sales', ['product_id'], unique=False)
    op.create_index(op.f('ix_fact_sales_run_id'), 'fact_sales', ['run_id'], unique=False)
    op.create_index(op.f('ix_fact_sales_source_id'), 'fact_sales', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fact_sales_source_id'), table_name='fact_sales')
    op.drop_index(op.f('ix_fact_sales_run_id'), table_name='fact_sales')
    op.drop_index(op.f('ix_fact_sales_product_id'), table_name='fact_sales')
    op.drop_index(op.f('ix_fact_sales_order_id'), table_name='fact_sales')
    op.drop_index(op.f('ix_fact_sales_id'), table_name='fact_sales')
    op.drop_index(op.f('ix_fact_sales_date_id'), table_name='fact_sales')
    op.drop_index(op.f('ix_fact_sales_customer_id'), table_name='fact_sales')
    op.drop_table('fact_sales')
    op.drop_index(op.f('ix_dim_products_product_name'), table_name='dim_products')
    op.drop_index(op.f('ix_dim_products_id'), table_name='dim_products')
    op.drop_table('dim_products')
    op.drop_index(op.f('ix_dim_dates_id'), table_name='dim_dates')
    op.drop_index(op.f('ix_dim_dates_calendar_date'), table_name='dim_dates')
    op.drop_table('dim_dates')
    op.drop_index(op.f('ix_dim_customers_id'), table_name='dim_customers')
    op.drop_index(op.f('ix_dim_customers_customer_name'), table_name='dim_customers')
    op.drop_table('dim_customers')
    # ### end Alembic commands ###
