"""add transformed rows table

Revision ID: b0ee18204dd1
Revises: 263138e18e28
Create Date: 2026-07-23 16:57:17.473907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0ee18204dd1'
down_revision: Union[str, Sequence[str], None] = '263138e18e28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transformed_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('data_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_runs.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['ingestion_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transformed_rows_id'), 'transformed_rows', ['id'], unique=False)
    op.create_index(op.f('ix_transformed_rows_run_id'), 'transformed_rows', ['run_id'], unique=False)
    op.create_index(op.f('ix_transformed_rows_source_id'), 'transformed_rows', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transformed_rows_source_id'), table_name='transformed_rows')
    op.drop_index(op.f('ix_transformed_rows_run_id'), table_name='transformed_rows')
    op.drop_index(op.f('ix_transformed_rows_id'), table_name='transformed_rows')
    op.drop_table('transformed_rows')
    # ### end Alembic commands ###
